/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.Employee.model.impl;

import com.Employee.model.emp;
import com.Employee.model.empModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the emp service. Represents a row in the &quot;DemoEmployee_emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>empModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link empImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see empImpl
 * @generated
 */
@JSON(strict = true)
public class empModelImpl extends BaseModelImpl<emp> implements empModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emp model instance should use the <code>emp</code> interface instead.
	 */
	public static final String TABLE_NAME = "DemoEmployee_emp";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"empId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdby", Types.BIGINT}, {"modifiedby", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"enrollmentNo", Types.VARCHAR}, {"firstName", Types.VARCHAR},
		{"lastName", Types.VARCHAR}, {"contactNo", Types.VARCHAR},
		{"city", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("empId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdby", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedby", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("enrollmentNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DemoEmployee_emp (uuid_ VARCHAR(75) null,empId LONG not null primary key,groupId LONG,companyId LONG,createdby LONG,modifiedby VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,enrollmentNo VARCHAR(75) null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,contactNo VARCHAR(75) null,city VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DemoEmployee_emp";

	public static final String ORDER_BY_JPQL = " ORDER BY emp.empId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DemoEmployee_emp.empId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CITY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public empModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _empId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmpId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _empId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return emp.class;
	}

	@Override
	public String getModelClassName() {
		return emp.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emp, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((emp)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<emp, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<emp, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((emp)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<emp, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<emp, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<emp, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<emp, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<emp, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<emp, Object>>();
		Map<String, BiConsumer<emp, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<emp, ?>>();

		attributeGetterFunctions.put("uuid", emp::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<emp, String>)emp::setUuid);
		attributeGetterFunctions.put("empId", emp::getEmpId);
		attributeSetterBiConsumers.put(
			"empId", (BiConsumer<emp, Long>)emp::setEmpId);
		attributeGetterFunctions.put("groupId", emp::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<emp, Long>)emp::setGroupId);
		attributeGetterFunctions.put("companyId", emp::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<emp, Long>)emp::setCompanyId);
		attributeGetterFunctions.put("createdby", emp::getCreatedby);
		attributeSetterBiConsumers.put(
			"createdby", (BiConsumer<emp, Long>)emp::setCreatedby);
		attributeGetterFunctions.put("modifiedby", emp::getModifiedby);
		attributeSetterBiConsumers.put(
			"modifiedby", (BiConsumer<emp, String>)emp::setModifiedby);
		attributeGetterFunctions.put("createDate", emp::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<emp, Date>)emp::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", emp::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<emp, Date>)emp::setModifiedDate);
		attributeGetterFunctions.put("enrollmentNo", emp::getEnrollmentNo);
		attributeSetterBiConsumers.put(
			"enrollmentNo", (BiConsumer<emp, String>)emp::setEnrollmentNo);
		attributeGetterFunctions.put("firstName", emp::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<emp, String>)emp::setFirstName);
		attributeGetterFunctions.put("lastName", emp::getLastName);
		attributeSetterBiConsumers.put(
			"lastName", (BiConsumer<emp, String>)emp::setLastName);
		attributeGetterFunctions.put("contactNo", emp::getContactNo);
		attributeSetterBiConsumers.put(
			"contactNo", (BiConsumer<emp, String>)emp::setContactNo);
		attributeGetterFunctions.put("city", emp::getCity);
		attributeSetterBiConsumers.put(
			"city", (BiConsumer<emp, String>)emp::setCity);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getEmpId() {
		return _empId;
	}

	@Override
	public void setEmpId(long empId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_empId = empId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getCreatedby() {
		return _createdby;
	}

	@Override
	public void setCreatedby(long createdby) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdby = createdby;
	}

	@JSON
	@Override
	public String getModifiedby() {
		if (_modifiedby == null) {
			return "";
		}
		else {
			return _modifiedby;
		}
	}

	@Override
	public void setModifiedby(String modifiedby) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedby = modifiedby;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getEnrollmentNo() {
		if (_enrollmentNo == null) {
			return "";
		}
		else {
			return _enrollmentNo;
		}
	}

	@Override
	public void setEnrollmentNo(String enrollmentNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enrollmentNo = enrollmentNo;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getContactNo() {
		if (_contactNo == null) {
			return "";
		}
		else {
			return _contactNo;
		}
	}

	@Override
	public void setContactNo(String contactNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactNo = contactNo;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCity() {
		return getColumnOriginalValue("city");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(emp.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), emp.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public emp toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, emp> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		empImpl empImpl = new empImpl();

		empImpl.setUuid(getUuid());
		empImpl.setEmpId(getEmpId());
		empImpl.setGroupId(getGroupId());
		empImpl.setCompanyId(getCompanyId());
		empImpl.setCreatedby(getCreatedby());
		empImpl.setModifiedby(getModifiedby());
		empImpl.setCreateDate(getCreateDate());
		empImpl.setModifiedDate(getModifiedDate());
		empImpl.setEnrollmentNo(getEnrollmentNo());
		empImpl.setFirstName(getFirstName());
		empImpl.setLastName(getLastName());
		empImpl.setContactNo(getContactNo());
		empImpl.setCity(getCity());

		empImpl.resetOriginalValues();

		return empImpl;
	}

	@Override
	public emp cloneWithOriginalValues() {
		empImpl empImpl = new empImpl();

		empImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		empImpl.setEmpId(this.<Long>getColumnOriginalValue("empId"));
		empImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		empImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		empImpl.setCreatedby(this.<Long>getColumnOriginalValue("createdby"));
		empImpl.setModifiedby(
			this.<String>getColumnOriginalValue("modifiedby"));
		empImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));
		empImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		empImpl.setEnrollmentNo(
			this.<String>getColumnOriginalValue("enrollmentNo"));
		empImpl.setFirstName(this.<String>getColumnOriginalValue("firstName"));
		empImpl.setLastName(this.<String>getColumnOriginalValue("lastName"));
		empImpl.setContactNo(this.<String>getColumnOriginalValue("contactNo"));
		empImpl.setCity(this.<String>getColumnOriginalValue("city"));

		return empImpl;
	}

	@Override
	public int compareTo(emp emp) {
		long primaryKey = emp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof emp)) {
			return false;
		}

		emp emp = (emp)object;

		long primaryKey = emp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<emp> toCacheModel() {
		empCacheModel empCacheModel = new empCacheModel();

		empCacheModel.uuid = getUuid();

		String uuid = empCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			empCacheModel.uuid = null;
		}

		empCacheModel.empId = getEmpId();

		empCacheModel.groupId = getGroupId();

		empCacheModel.companyId = getCompanyId();

		empCacheModel.createdby = getCreatedby();

		empCacheModel.modifiedby = getModifiedby();

		String modifiedby = empCacheModel.modifiedby;

		if ((modifiedby != null) && (modifiedby.length() == 0)) {
			empCacheModel.modifiedby = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			empCacheModel.createDate = createDate.getTime();
		}
		else {
			empCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			empCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			empCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		empCacheModel.enrollmentNo = getEnrollmentNo();

		String enrollmentNo = empCacheModel.enrollmentNo;

		if ((enrollmentNo != null) && (enrollmentNo.length() == 0)) {
			empCacheModel.enrollmentNo = null;
		}

		empCacheModel.firstName = getFirstName();

		String firstName = empCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			empCacheModel.firstName = null;
		}

		empCacheModel.lastName = getLastName();

		String lastName = empCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			empCacheModel.lastName = null;
		}

		empCacheModel.contactNo = getContactNo();

		String contactNo = empCacheModel.contactNo;

		if ((contactNo != null) && (contactNo.length() == 0)) {
			empCacheModel.contactNo = null;
		}

		empCacheModel.city = getCity();

		String city = empCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			empCacheModel.city = null;
		}

		return empCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emp, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((emp)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<emp, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<emp, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emp, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((emp)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, emp>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					emp.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _empId;
	private long _groupId;
	private long _companyId;
	private long _createdby;
	private String _modifiedby;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _enrollmentNo;
	private String _firstName;
	private String _lastName;
	private String _contactNo;
	private String _city;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<emp, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((emp)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("empId", _empId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdby", _createdby);
		_columnOriginalValues.put("modifiedby", _modifiedby);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("enrollmentNo", _enrollmentNo);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("contactNo", _contactNo);
		_columnOriginalValues.put("city", _city);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("empId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createdby", 16L);

		columnBitmasks.put("modifiedby", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("enrollmentNo", 256L);

		columnBitmasks.put("firstName", 512L);

		columnBitmasks.put("lastName", 1024L);

		columnBitmasks.put("contactNo", 2048L);

		columnBitmasks.put("city", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private emp _escapedModel;

}