/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.inexture.studentService.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StudentDemo service. Represents a row in the &quot;stud_StudentDemo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.inexture.studentService.model.impl.StudentDemoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.inexture.studentService.model.impl.StudentDemoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentDemo
 * @generated
 */
@ProviderType
public interface StudentDemoModel extends BaseModel<StudentDemo>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student demo model instance should use the {@link StudentDemo} interface instead.
	 */

	/**
	 * Returns the primary key of this student demo.
	 *
	 * @return the primary key of this student demo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student demo.
	 *
	 * @param primaryKey the primary key of this student demo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student ID of this student demo.
	 *
	 * @return the student ID of this student demo
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student demo.
	 *
	 * @param studentId the student ID of this student demo
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the group ID of this student demo.
	 *
	 * @return the group ID of this student demo
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this student demo.
	 *
	 * @param groupId the group ID of this student demo
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this student demo.
	 *
	 * @return the company ID of this student demo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this student demo.
	 *
	 * @param companyId the company ID of this student demo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the createdby of this student demo.
	 *
	 * @return the createdby of this student demo
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this student demo.
	 *
	 * @param createdby the createdby of this student demo
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the modifiedby of this student demo.
	 *
	 * @return the modifiedby of this student demo
	 */
	@AutoEscape
	public String getModifiedby();

	/**
	 * Sets the modifiedby of this student demo.
	 *
	 * @param modifiedby the modifiedby of this student demo
	 */
	public void setModifiedby(String modifiedby);

	/**
	 * Returns the create date of this student demo.
	 *
	 * @return the create date of this student demo
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this student demo.
	 *
	 * @param createDate the create date of this student demo
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this student demo.
	 *
	 * @return the modified date of this student demo
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student demo.
	 *
	 * @param modifiedDate the modified date of this student demo
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the enrollment no of this student demo.
	 *
	 * @return the enrollment no of this student demo
	 */
	@AutoEscape
	public String getEnrollmentNo();

	/**
	 * Sets the enrollment no of this student demo.
	 *
	 * @param enrollmentNo the enrollment no of this student demo
	 */
	public void setEnrollmentNo(String enrollmentNo);

	/**
	 * Returns the first name of this student demo.
	 *
	 * @return the first name of this student demo
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this student demo.
	 *
	 * @param firstName the first name of this student demo
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this student demo.
	 *
	 * @return the last name of this student demo
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this student demo.
	 *
	 * @param lastName the last name of this student demo
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the contact no of this student demo.
	 *
	 * @return the contact no of this student demo
	 */
	@AutoEscape
	public String getContactNo();

	/**
	 * Sets the contact no of this student demo.
	 *
	 * @param contactNo the contact no of this student demo
	 */
	public void setContactNo(String contactNo);

	/**
	 * Returns the city of this student demo.
	 *
	 * @return the city of this student demo
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this student demo.
	 *
	 * @param city the city of this student demo
	 */
	public void setCity(String city);

	@Override
	public StudentDemo cloneWithOriginalValues();

}